-- GENERATED by theme/build.py from theme/palette.json — do not edit.
return {
  mode = "dark",
  fg             = "#e8e8e8",
  fg_muted       = "#999999",
  fg_faint       = "#6e6e6e",
  divider        = "#404040",
  surface        = "#242424",
  surface_active = "#303030",
  red            = "#e06060",
  green          = "#7fd47f",
  yellow         = "#e6d06a",
  blue           = "#4c7ad4",
  magenta        = "#d48ad4",
  cyan           = "#6dcaca",
  orange         = "#f0a86a",
  paper = { lo = "#181818", hi = "#1c1c1c", noise = 200 },
}
