-- GENERATED by theme/build.py from theme/palette.json — do not edit.
return {
  fg             = "#1a1a1a",
  fg_muted       = "#404040",
  fg_faint       = "#595959",
  divider        = "#a3a3a3",
  surface        = "#e4e4e4",
  surface_active = "#ececec",
  red            = "#8f2727",
  green          = "#225e31",
  yellow         = "#705214",
  blue           = "#204a87",
  magenta        = "#752c61",
  cyan           = "#175e5e",
  orange         = "#9c4314",
  paper = { lo = "#d2d2d2", hi = "#d6d6d6", noise = 200 },
}
