#!/usr/bin/env python3
"""Render theme/palette.json into the per-tool files that actually get loaded.

Canonical source:  theme/palette.json  (two modes: "light" and "dark")

Generated outputs (one per mode, do not hand-edit):
  theme/palette.light.sh    theme/palette.dark.sh      -- THEME_* vars for zsh
  wezterm/lua/palette_light.lua  wezterm/lua/palette_dark.lua
  nvim/lua/palette_light.lua     nvim/lua/palette_dark.lua
  claude/themes/new-wave.json    claude/themes/new-wave-dark.json  -- Claude Code

Hand-written shims (NOT generated, safe to edit):
  theme/palette.sh          sources the active mode's palette.<mode>.sh
  wezterm/lua/palette.lua    returns the active mode's palette_<mode>
  nvim/lua/palette.lua       returns the active mode's palette_<mode>

Claude Code has no runtime shim: its custom themes ride the terminal's ANSI
palette (base "<mode>-ansi"), so they follow WezTerm's colours, and the `theme`
command repoints ~/.claude/settings.json at the matching one.

The active mode is whatever the `theme` command last wrote to
$XDG_CACHE_HOME/dotfiles/theme-mode (default: light).

Run this after editing palette.json. install.sh runs it too, so a fresh clone is
always consistent. Every generated file is overwritten wholesale.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "theme" / "palette.json"

BANNER_HASH = "# GENERATED by theme/build.py from theme/palette.json — do not edit.\n"
BANNER_LUA = "-- GENERATED by theme/build.py from theme/palette.json — do not edit.\n"

MODES = ("light", "dark")


def load():
    data = json.loads(SRC.read_text())
    return {mode: data[mode]["colors"] for mode in MODES}


def render_sh(mode, colors):
    lines = [BANNER_HASH, f"export THEME_MODE='{mode}'\n"]
    for name, hex_ in colors.items():
        lines.append(f"export THEME_{name.upper()}='{hex_}'\n")
    return "".join(lines)


def render_claude(mode, colors):
    """A Claude Code custom theme. base "<mode>-ansi" routes every semantic colour
    through the terminal's ANSI palette (so it tracks WezTerm, which is generated
    from this same file). Only the chrome that ANSI can't express well — panel and
    message backgrounds, borders, knockout text — is pinned to palette hexes."""
    slug = "new-wave" if mode == "light" else "new-wave-dark"
    name = "New Wave" if mode == "light" else "New Wave Dark"
    theme = {
        "name": name,
        "base": f"{mode}-ansi",
        "overrides": {
            "background": colors["bg"],
            "inverseText": colors["bg"],
            "userMessageBackground": colors["surface"],
            "userMessageBackgroundHover": colors["surface_active"],
            "composerSidebarBackground": colors["surface"],
            "bashMessageBackgroundColor": colors["surface"],
            "memoryBackgroundColor": colors["surface"],
            "selectionBg": colors["surface_active"],
            "promptBorder": colors["divider"],
            "promptBorderShimmer": colors["fg_faint"],
            "rate_limit_empty": colors["divider"],
        },
    }
    return slug, json.dumps(theme, indent=2) + "\n"


def render_lua(mode, colors):
    lines = [BANNER_LUA, "return {\n", f'  mode = "{mode}",\n']
    width = max(len(n) for n in colors)
    for name, hex_ in colors.items():
        lines.append(f'  {name.ljust(width)} = "{hex_}",\n')
    lines.append("}\n")
    return "".join(lines)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def main():
    modes = load()
    print(f"theme: {SRC.relative_to(ROOT)} -> {len(modes) * 4} files")
    for mode, colors in modes.items():
        write(ROOT / "theme" / f"palette.{mode}.sh", render_sh(mode, colors))
        write(ROOT / "wezterm" / "lua" / f"palette_{mode}.lua", render_lua(mode, colors))
        write(ROOT / "nvim" / "lua" / f"palette_{mode}.lua", render_lua(mode, colors))
        slug, body = render_claude(mode, colors)
        write(ROOT / "claude" / "themes" / f"{slug}.json", body)


if __name__ == "__main__":
    main()
