#!/usr/bin/env python3
"""Render theme/palette.json into the per-tool files that actually get loaded.

Canonical source:  theme/palette.json  (two modes: "light" and "dark")

Generated outputs (one pair per mode, do not hand-edit):
  theme/palette.light.sh    theme/palette.dark.sh      -- THEME_* vars for zsh
  wezterm/lua/palette_light.lua  wezterm/lua/palette_dark.lua
  nvim/lua/palette_light.lua     nvim/lua/palette_dark.lua

Hand-written shims (NOT generated, safe to edit):
  theme/palette.sh          sources the active mode's palette.<mode>.sh
  wezterm/lua/palette.lua    returns the active mode's palette_<mode>
  nvim/lua/palette.lua       returns the active mode's palette_<mode>

The active mode is whatever the `theme` command last wrote to
$XDG_CACHE_HOME/dotfiles/theme-mode (default: light).

Run this after editing palette.json. install.sh runs it too, so a fresh clone is
always consistent. Every generated file is overwritten wholesale.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "theme" / "palette.json"

BANNER_HASH = "# GENERATED by theme/build.py from theme/palette.json — do not edit.\n"
BANNER_LUA = "-- GENERATED by theme/build.py from theme/palette.json — do not edit.\n"

MODES = ("light", "dark")


def load():
    data = json.loads(SRC.read_text())
    return {mode: (data[mode]["colors"], data[mode]["paper"]) for mode in MODES}


def render_sh(mode, colors, paper):
    lines = [BANNER_HASH, f"export THEME_MODE='{mode}'\n"]
    for name, hex_ in colors.items():
        lines.append(f"export THEME_{name.upper()}='{hex_}'\n")
    lines.append(f"export THEME_PAPER_LO='{paper['lo']}'\n")
    lines.append(f"export THEME_PAPER_HI='{paper['hi']}'\n")
    lines.append(f"export THEME_PAPER_NOISE='{paper['noise']}'\n")
    return "".join(lines)


def render_lua(mode, colors, paper):
    lines = [BANNER_LUA, "return {\n", f'  mode = "{mode}",\n']
    width = max(len(n) for n in colors)
    for name, hex_ in colors.items():
        lines.append(f'  {name.ljust(width)} = "{hex_}",\n')
    lines.append(
        f'  paper = {{ lo = "{paper["lo"]}", hi = "{paper["hi"]}", '
        f'noise = {paper["noise"]} }},\n'
    )
    lines.append("}\n")
    return "".join(lines)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def main():
    modes = load()
    print(f"theme: {SRC.relative_to(ROOT)} -> {len(modes) * 3} files")
    for mode, (colors, paper) in modes.items():
        write(ROOT / "theme" / f"palette.{mode}.sh", render_sh(mode, colors, paper))
        write(ROOT / "wezterm" / "lua" / f"palette_{mode}.lua", render_lua(mode, colors, paper))
        write(ROOT / "nvim" / "lua" / f"palette_{mode}.lua", render_lua(mode, colors, paper))


if __name__ == "__main__":
    main()
