#!/usr/bin/env python3
"""Render theme/palette.json into the per-tool files that actually get loaded.

Canonical source:  theme/palette.json
Generated outputs:
  theme/palette.sh        -- sourced by zsh/.zshrc and zsh/.p10k.zsh (THEME_* vars)
  wezterm/lua/palette.lua  -- required by the WezTerm config
  nvim/lua/palette.lua     -- required by init.lua

Run it after editing palette.json. install.sh runs it too, so a fresh clone is
always consistent. Every output file is overwritten wholesale; don't hand-edit them.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "theme" / "palette.json"

BANNER_HASH = "# GENERATED by theme/build.py from theme/palette.json — do not edit.\n"
BANNER_LUA = "-- GENERATED by theme/build.py from theme/palette.json — do not edit.\n"


def load():
    data = json.loads(SRC.read_text())
    return data["colors"], data["paper"]


def render_sh(colors, paper):
    lines = [BANNER_HASH]
    for name, hex_ in colors.items():
        lines.append(f"THEME_{name.upper()}='{hex_}'\n")
    lines.append(f"THEME_PAPER_LO='{paper['lo']}'\n")
    lines.append(f"THEME_PAPER_HI='{paper['hi']}'\n")
    lines.append(f"THEME_PAPER_NOISE='{paper['noise']}'\n")
    return "".join(lines)


def render_lua(colors, paper):
    lines = [BANNER_LUA, "return {\n"]
    width = max(len(n) for n in colors)
    for name, hex_ in colors.items():
        lines.append(f'  {name.ljust(width)} = "{hex_}",\n')
    lines.append(
        f'  paper = {{ lo = "{paper["lo"]}", hi = "{paper["hi"]}", '
        f'noise = {paper["noise"]} }},\n'
    )
    lines.append("}\n")
    return "".join(lines)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def main():
    colors, paper = load()
    print(f"theme: {SRC.relative_to(ROOT)} -> 3 files")
    write(ROOT / "theme" / "palette.sh", render_sh(colors, paper))
    write(ROOT / "wezterm" / "lua" / "palette.lua", render_lua(colors, paper))
    write(ROOT / "nvim" / "lua" / "palette.lua", render_lua(colors, paper))


if __name__ == "__main__":
    main()
