-- GENERATED by theme/build.py from theme/palette.json — do not edit.
return {
  mode = "light",
  bg             = "#f4f4f4",
  fg             = "#1a1a1a",
  fg_muted       = "#666666",
  fg_faint       = "#999999",
  divider        = "#bdbdbd",
  surface        = "#ebebeb",
  surface_active = "#cecece",
  red            = "#cc3f3f",
  green          = "#5ca85c",
  yellow         = "#a8922e",
  blue           = "#3d6fd4",
  magenta        = "#a95cb8",
  cyan           = "#3d9a9a",
  orange         = "#c47a3a",
}
